# Generated by Django 3.0.5 on 2020-04-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='books.Author'),
            preserve_default='true',
        ),
    ]
